odim-5243: Validate Simple update post request
hemkapoor/ODIM pull request #18
Opened 2022-03-10 07:49 UTC by hemkapoor

Validate Simple update post request

2022-03-10 08:00 UTC, irappa-pattar requested changes

2022-03-10 08:00 UTC, irappa-pattar commented on svc-update/update/simpleUpdate.go
> +				errMsg := "'Targets' parameter should be of type string array"
correct the error message

2022-03-10 08:46 UTC, irappa-pattar approved these changes

2022-03-15 05:10 UTC, jeevan-kamkar approved these changes

2022-03-15 05:49 UTC, lpooja approved these changes

2022-03-15 06:23 UTC, amar-shalgar approved these changes

2022-03-15 06:23 UTC, merged