odim-6871: Resolve the vulnerabilities found in github code scanning
hemkapoor/ODIM pull request #36
Opened 2022-12-07 11:06 UTC by hemkapoor

Resolve the vulnerabilities found in github code scanning

2022-12-07 11:14 UTC, AngithCJ approved these changes

2022-12-07 12:01 UTC, chauberahul1993 approved these changes

2022-12-08 04:00 UTC, amar-shalgar requested changes

2022-12-08 04:00 UTC, amar-shalgar commented on odim-controller/scripts/odim-controller.py
> +				logger.critical("Redis In-Memory Password File Path does not exist, exiting!!!")
Please look into alphabet casing

2022-12-08 04:00 UTC, amar-shalgar commented on odim-controller/scripts/odim-controller.py
> +				logger.critical("Redis On-Disk Password File Path does not exist, exiting!!!")
Look into alphabet casing

2022-12-08 04:00 UTC, amar-shalgar commented on lib-utilities/logs/logging.go
> +	if reqStr == "" {
This change may require changes in https://github.com/ODIM-Project/ODIM/blob/development/lib-utilities/logs/logging.go#L142

2022-12-08 06:16 UTC, hemkapoor commented on lib-utilities/logs/logging.go
> +	if reqStr == "" {
Already removed

2022-12-08 06:18 UTC, amar-shalgar approved these changes

2022-12-08 06:18 UTC, merged