odim-5449: Update registry version to latest
hemkapoor/ODIM pull request #5
Opened 2022-01-03 10:05 UTC by hemkapoor

Update registry version to latest

2022-01-04 03:52 UTC, irappa-pattar requested changes
I would recommend using separate const or var to define **Base.1.11.0** and use it across, so whenever the version is updated, we no need to update everywhere.

2022-01-04 05:37 UTC, amar-shalgar approved these changes
LGTM

2022-01-04 08:24 UTC, irappa-pattar approved these changes

2022-01-07 05:41 UTC, jeevan-kamkar approved these changes

2022-01-10 05:15 UTC, shivacharanms approved these changes

2022-01-10 05:16 UTC, merged