odim-5453: Add ManagerForChassis and ManagerForServer details under manager ID
hemkapoor/ODIM pull request #6
Opened 2022-01-25 05:33 UTC by hemkapoor

Add ManagerForChassis and ManagerForServer details under manager ID

2022-01-27 08:02 UTC, jeevan-kamkar requested changes
Address the requested changes

2022-01-27 08:02 UTC, jeevan-kamkar commented on svc-aggregation/system/addcompute.go
> +	chassis["@odata.id"] = "/redfish/v1/Chassis/" + aggregationSourceID
use the chassis and manager from the  chassisList and managersList https://github.com/hemkapoor/ODIM/pull/6/files#diff-a335139c65eea95bdc53f02d1365cc8cb68e150636ec51806a3bf60f6f1e54f7R273

2022-01-27 08:02 UTC, jeevan-kamkar commented on svc-aggregation/agmodel/system.go
> +func GetManagerByURL(url string) (string, *errors.Error) {
there is no need of new function use this function 
https://github.com/ODIM-Project/ODIM/blob/development/svc-aggregation/agmodel/system.go#L167

2022-01-27 08:02 UTC, jeevan-kamkar commented on svc-aggregation/agmodel/system.go
> +func UpdateManagerData(key string, updateData map[string]interface{}, table string) error {
no need of new function use this function 
https://github.com/ODIM-Project/ODIM/blob/development/svc-aggregation/agmodel/system.go#L276

2022-01-27 10:21 UTC, shivacharanms commented on svc-aggregation/agmodel/system.go
> +	log.Info("Update MAnager Data...")
Add meaningful logs as got a review comment from our demo

2022-01-31 09:16 UTC, jeevan-kamkar requested changes
Address the requested changes

2022-01-31 09:16 UTC, jeevan-kamkar commented on svc-aggregation/system/addcompute.go
> +		chassis[index] = make(map[string]interface{})
instead of  this replace it as `listOfChassis=append(listOfChassis,map[string]string{
		"@odata.id":val,
		}
		)`

2022-01-31 09:16 UTC, jeevan-kamkar commented on svc-aggregation/system/addcompute.go
> +		listOfServer = append(listOfServer, server[index])
listOfServer=append(listOfServer,map[string]string{
		"@odata.id":val,
		}
		)

2022-02-01 06:02 UTC, jeevan-kamkar approved these changes

2022-02-01 12:57 UTC, shivacharanms approved these changes

2022-02-04 07:53 UTC, merged